# site settings

title: Zyxw_feng
subtitle: Just now or never
welcome_message: Welcome to my blog
description: A front-end developer
author: 
  name: zyxw_feng
  email: zyxw_feng@163.com
  github: Zyxfeng
  weibo: https://weibo.com/p/1005053123140125

# bulid settings
permalink: /:year/:month/:day/:title/                 #博文固定链接
paginate: 10                                          #分页时每页博文
paginate_path: "/page/:num/"

markdown: kramdown
highlighter: rouge
auto: true
cover_color: lightgrey

blog_button:
  title: Blog
  description: Visit blog